// src/routes/setup-session/[seedId]/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { pb } from '$lib/pb';
  import { userCookie } from '$lib/stores';
  import { apClient } from '$lib/ap';
  import { fetchCyclingIntersections, shuffleArray } from '$lib/osm';
  import { updateSessionWithMapDetails } from '$lib/db';
  import 'leaflet/dist/leaflet.css';

  const seedId = $page.params.seedId;

  let mapElement: HTMLElement;
  let map: any;
  let centerMarker: any = null;
  let radiusCircle: any = null;
  let L: any;

  // Form state
  let centerLat = 40.4406; // Default Pittsburgh
  let centerLon = -79.9959;
  let radius = 5000;
  let addressQuery = '';

  // UI state
  let loadError = '';
  let isGeocoding = false;
  let geocodeError = '';
  let isLocating = false;
  let locationError = '';
  let isGenerating = false;
  let generationError = '';

  // Progress tracking
  let generationStatus = '';
  let generationProgress = 0; // 0-100

  // Session data
  let sessionId = '';
  let apItemCount = 0;

  onMount(async () => {
    try {
      // Verify AP is connected and get item count
      if (!apClient.authenticated) {
        loadError = 'Not connected to Archipelago. Please connect first.';
        return;
      }

      apItemCount = apClient.items.received.length;
      if (apItemCount === 0) {
        loadError = 'No items received from Archipelago. Check your connection.';
        return;
      }

      console.log(`[Setup] AP item count: ${apItemCount}`);

      // Initialize map
      const leafletMod = await import('leaflet');
      L = leafletMod.default ?? leafletMod;
      window.L = L;
      map = L.map(mapElement).setView([centerLat, centerLon], 12);

      L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);

      updateMapPin(centerLat, centerLon);

      map.on('click', (e: any) => {
        centerLat = e.latlng.lat;
        centerLon = e.latlng.lng;
        updateMapPin(centerLat, centerLon);
      });
    } catch (error: any) {
      loadError = error?.message || 'Failed to initialize setup page.';
      console.error('[Setup] Init error:', error);
    }
  });

  function updateMapPin(lat: number, lon: number) {
    if (centerMarker) {
      centerMarker.setLatLng([lat, lon]);
    } else {
      centerMarker = L.marker([lat, lon], {
        icon: L.icon({
          iconUrl: '/start.png',
          iconSize: [25, 41],
          iconAnchor: [12, 41]
        })
      }).addTo(map);
    }

    if (radiusCircle) {
      radiusCircle.setLatLng([lat, lon]);
      radiusCircle.setRadius(radius);
    } else {
      radiusCircle = L.circle([lat, lon], {
        radius: radius,
        color: 'red',
        fillColor: '#f03',
        fillOpacity: 0.1
      }).addTo(map);
    }
  }

  $: {
    if (map && centerLat && centerLon && radius) {
      updateMapPin(centerLat, centerLon);
    }
  }

  async function searchAddress() {
    if (!addressQuery.trim()) return;
    isGeocoding = true;
    geocodeError = '';
    try {
      const res = await fetch(
        `/api/geocode?q=${encodeURIComponent(addressQuery.trim())}&limit=1&locale=en`
      );
      if (!res.ok) throw new Error('Geocoding request failed.');
      const data = await res.json();
      if (!data.hits || data.hits.length === 0) {
        geocodeError = 'No results found. Try a different address.';
        return;
      }
      const { lat, lng } = data.hits[0].point;
      centerLat = lat;
      centerLon = lng;
      map.setView([centerLat, centerLon], 13);
      updateMapPin(centerLat, centerLon);
    } catch (err: any) {
      geocodeError = err.message || 'Failed to geocode address.';
    } finally {
      isGeocoding = false;
    }
  }

  function useMyLocation() {
    if (!navigator.geolocation) {
      locationError = 'Geolocation is not supported by your browser.';
      return;
    }
    isLocating = true;
    locationError = '';
    navigator.geolocation.getCurrentPosition(
      (pos) => {
        centerLat = pos.coords.latitude;
        centerLon = pos.coords.longitude;
        map.setView([centerLat, centerLon], 13);
        updateMapPin(centerLat, centerLon);
        isLocating = false;
      },
      (err) => {
        locationError = err.message || 'Could not retrieve your location.';
        isLocating = false;
      }
    );
  }

  async function generateSession() {
    isGenerating = true;
    generationError = '';
    generationProgress = 0;
    generationStatus = '';

    try {
      const userId = $userCookie?.user?.id;
      if (!userId) {
        throw new Error('Not logged in.');
      }

      // Step 1: Fetch intersections
      generationStatus = 'Fetching cycling intersections...';
      generationProgress = 25;

      const intersections = await fetchCyclingIntersections(centerLat, centerLon, radius);

      if (intersections.length < apItemCount) {
        generationError = `Found only ${intersections.length} intersections, but AP has ${apItemCount} items. Increase radius or decrease the AP check count.`;
        isGenerating = false;
        return;
      }

      // Step 2: Create game session
      generationStatus = 'Creating game session...';
      generationProgress = 40;

      const sessionRecord = await pb.collection('game_sessions').create({
        user: userId,
        ap_seed_name: seedId,
        ap_server_url: apClient.room.seedName ? 'connected' : '',  // Placeholder
        ap_slot_name: 'Setup',
        status: 'SetupInProgress',
        center_lat: centerLat,
        center_lon: centerLon,
        radius: radius
      });

      sessionId = sessionRecord.id;

      // Step 3: Create nodes
      generationStatus = `Creating ${apItemCount} nodes...`;
      generationProgress = 50;

      const selectedNodes = shuffleArray(intersections).slice(0, apItemCount);

      for (let i = 0; i < selectedNodes.length; i++) {
        const node = selectedNodes[i];
        let nodeName = `OSM Node ${node.id}`;

        try {
          const res = await fetch(
            `/api/geocode?q=${node.lat},${node.lon}&limit=1&locale=en`
          );
          if (res.ok) {
            const data = await res.json();
            if (data.hits && data.hits.length > 0) {
              nodeName = data.hits[0].name;
            }
          }
        } catch (e) {
          console.warn('Reverse geocode failed for node', node.id, e);
        }

        await pb.collection('map_nodes').create({
          session: sessionId,
          ap_location_id: 800000 + (i + 1),
          osm_node_id: node.id.toString(),
          name: nodeName,
          lat: node.lat,
          lon: node.lon,
          state: 'Hidden'
        }, { requestKey: `map_node_${i}` });

        // Update progress
        const nodeProgress = ((i + 1) / selectedNodes.length) * 40; // 40% for nodes
        generationProgress = 50 + nodeProgress;

        // Small delay to avoid overwhelming the API
        await new Promise(r => setTimeout(r, 50));
      }

      // Step 4: Sync state with AP
      generationStatus = 'Syncing with Archipelago...';
      generationProgress = 95;

      // Call syncArchipelagoState to set initial node states
      const { syncArchipelagoState } = await import('$lib/ap');
      // Note: syncArchipelagoState is private, so this might not work
      // Instead, we'll rely on the game page to sync on load

      // Step 5: Update session to Active
      generationStatus = 'Finalizing...';
      generationProgress = 99;

      await updateSessionWithMapDetails(sessionId, centerLat, centerLon, radius);

      generationProgress = 100;
      generationStatus = 'Session created!';

      // Redirect to game
      setTimeout(() => {
        goto(`/game/${sessionId}`);
      }, 500);
    } catch (error: any) {
      console.error('[Setup] Generation error:', error);
      generationError = error?.message || 'Failed to create session.';
    } finally {
      isGenerating = false;
    }
  }
</script>

<svelte:head>
  <title>Set Up Bikeapelago Session</title>
</svelte:head>

<div class="p-6 text-white max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-6">
  <!-- Left panel: Form -->
  <div class="bg-neutral-800 p-6 rounded-lg shadow-lg">
    <h1 class="text-3xl font-bold mb-2 text-orange-500">Set Up Your Session</h1>
    <p class="text-neutral-400 text-sm mb-6">
      Choose your center point on the map to generate {apItemCount} intersections
    </p>

    {#if loadError}
      <div class="mb-4 p-3 bg-red-900/50 border border-red-500 text-red-200 rounded">
        {loadError}
      </div>
    {:else}
      <div class="space-y-4">
        <!-- Address search -->
        <div>
          <label class="block text-sm font-medium mb-1">Search Address</label>
          <div class="flex gap-2">
            <input
              type="text"
              placeholder="Search address or place…"
              bind:value={addressQuery}
              on:keydown={(e) => e.key === 'Enter' && (e.preventDefault(), searchAddress())}
              disabled={isGeocoding || isGenerating}
              class="flex-1 bg-neutral-700 border border-neutral-600 rounded px-3 py-2 text-white placeholder-neutral-400 focus:outline-none focus:border-orange-500 disabled:opacity-50"
            />
            <button
              type="button"
              on:click={searchAddress}
              disabled={isGeocoding || !addressQuery.trim() || isGenerating}
              class="bg-neutral-700 hover:bg-neutral-600 border border-neutral-600 text-white font-medium px-4 py-2 rounded transition disabled:opacity-50 whitespace-nowrap"
            >
              {isGeocoding ? 'Searching…' : 'Search'}
            </button>
          </div>
          {#if geocodeError}
            <p class="mt-1 text-xs text-red-400">{geocodeError}</p>
          {/if}
        </div>

        <!-- Use my location -->
        <button
          type="button"
          on:click={useMyLocation}
          disabled={isLocating || isGenerating}
          class="w-full flex items-center justify-center gap-2 bg-neutral-700 hover:bg-neutral-600 border border-neutral-600 text-white text-sm font-medium px-4 py-2 rounded transition disabled:opacity-50"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="w-4 h-4 text-orange-400 shrink-0"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="12" cy="12" r="3" />
            <path d="M12 2v3M12 19v3M2 12h3M19 12h3" />
          </svg>
          {isLocating ? 'Locating…' : 'Use My Location'}
        </button>

        <!-- Radius control -->
        <div>
          <label class="block text-sm font-medium mb-2">Radius (meters)</label>
          <input
            type="range"
            min="100"
            max="50000"
            step="100"
            bind:value={radius}
            disabled={isGenerating}
            class="w-full"
          />
          <p class="text-xs text-neutral-400 mt-1">{radius.toLocaleString()} meters</p>
        </div>

        <!-- Status -->
        <div class="pt-2 border-t border-neutral-600">
          <p class="text-sm text-neutral-300 mb-2">
            Intersections needed: <strong>{apItemCount}</strong>
          </p>
        </div>

        <!-- Generation progress -->
        {#if isGenerating}
          <div class="space-y-2">
            <p class="text-sm text-orange-400">{generationStatus}</p>
            <div class="w-full bg-neutral-700 rounded h-2 overflow-hidden">
              <div
                class="bg-orange-500 h-full transition-all"
                style="width: {generationProgress}%"
              />
            </div>
            <p class="text-xs text-neutral-400 text-right">{Math.round(generationProgress)}%</p>
          </div>
        {/if}

        {#if generationError}
          <div class="p-3 bg-red-900/50 border border-red-500 text-red-200 rounded text-sm">
            {generationError}
          </div>
        {/if}

        <!-- Generate button -->
        <button
          on:click={generateSession}
          disabled={isGenerating}
          class="w-full bg-orange-600 hover:bg-orange-500 text-white font-bold py-3 px-4 rounded transition disabled:opacity-50"
        >
          {isGenerating ? 'Generating…' : 'Create Session & Play'}
        </button>

        <p class="text-xs text-neutral-400">Click on the map to set the center point for node generation.</p>
      </div>
    {/if}
  </div>

  <!-- Right panel: Map -->
  <div class="bg-neutral-800 rounded-lg shadow-lg overflow-hidden h-[600px] border border-neutral-700">
    <div bind:this={mapElement} class="w-full h-full" />
  </div>
</div>

<style>
  :global(html, body) {
    overflow: auto;
  }
</style>

// nextjsmigration/app/setup-session/[seedId]/page.tsx
"use client";

import { useEffect, useState, useRef } from 'react';
import { useRouter, useParams } from 'next/navigation';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { fetchCyclingIntersections, shuffleArray } from '@/lib/osm';
import { pb } from '@/lib/database';

export default function SetupSessionPage() {
  const router = useRouter();
  const params = useParams();
  const seedId = params.seedId as string;

  const mapRef = useRef<HTMLDivElement>(null);
  const [map, setMap] = useState<L.Map | null>(null);
  const [centerMarker, setCenterMarker] = useState<L.Marker | null>(null);
  const [radiusCircle, setRadiusCircle] = useState<L.Circle | null>(null);

  const [centerLat, setCenterLat] = useState(40.4406);
  const [centerLon, setCenterLon] = useState(-79.9959);
  const [radius, setRadius] = useState(5000);
  const [addressQuery, setAddressQuery] = useState('');

  const [loadError, setLoadError] = useState('');
  const [isGeocoding, setIsGeocoding] = useState(false);
  const [geocodeError, setGeocodeError] = useState('');
  const [isLocating, setIsLocating] = useState(false);
  const [locationError, setLocationError] = useState('');

  const [isGenerating, setIsGenerating] = useState(false);
  const [generationError, setGenerationError] = useState('');

  const [sessionData, setSessionData] = useState<any>(null);

  useEffect(() => {
    async function loadSession() {
      try {
        const session = await pb.collection('game_sessions').getOne(seedId);
        setSessionData(session);
        if (session.status === 'Active') {
          router.push(`/game/${seedId}`);
        }
      } catch (err: any) {
        setLoadError(err.message || 'Session not found.');
      }
    }
    loadSession();
  }, [seedId, router]);

  useEffect(() => {
    if (!mapRef.current || map) return;

    // Use custom marker icon to avoid missing default image issues in Next.js
    const defaultIcon = L.icon({
      iconUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',
      shadowUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',
      iconSize: [25, 41],
      iconAnchor: [12, 41],
    });
    L.Marker.prototype.options.icon = defaultIcon;

    const newMap = L.map(mapRef.current).setView([centerLat, centerLon], 13);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19 }).addTo(newMap);

    const marker = L.marker([centerLat, centerLon], { draggable: true }).addTo(newMap);
    const circle = L.circle([centerLat, centerLon], { radius, color: '#e67e22', fillColor: '#e67e22', fillOpacity: 0.1 }).addTo(newMap);

    marker.on('dragend', function (e) {
      const pos = e.target.getLatLng();
      setCenterLat(pos.lat);
      setCenterLon(pos.lng);
      circle.setLatLng(pos);
      newMap.panTo(pos);
    });

    setMap(newMap);
    setCenterMarker(marker);
    setRadiusCircle(circle);

    return () => {
      newMap.remove();
    };
  }, []);

  useEffect(() => {
    if (radiusCircle && map) {
      radiusCircle.setRadius(radius);
      map.fitBounds(radiusCircle.getBounds(), { padding: [20, 20] });
    }
  }, [radius, radiusCircle, map]);

  const handleGeocode = async () => {
    if (!addressQuery.trim()) return;
    setIsGeocoding(true);
    setGeocodeError('');
    try {
      const res = await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(addressQuery)}`);
      if (!res.ok) throw new Error('Geocoding failed');
      const data = await res.json();
      if (data && data.length > 0) {
        const lat = parseFloat(data[0].lat);
        const lon = parseFloat(data[0].lon);
        updateMapCenter(lat, lon);
      } else {
        setGeocodeError('Address not found.');
      }
    } catch (err) {
      setGeocodeError('Error searching address.');
    } finally {
      setIsGeocoding(false);
    }
  };

  const getUserLocation = () => {
    setIsLocating(true);
    setLocationError('');
    if ('geolocation' in navigator) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          updateMapCenter(position.coords.latitude, position.coords.longitude);
          setIsLocating(false);
        },
        (error) => {
          setLocationError('Could not get your location. Please check your browser permissions.');
          setIsLocating(false);
        },
        { enableHighAccuracy: true, timeout: 5000, maximumAge: 0 }
      );
    } else {
      setLocationError('Geolocation is not supported by your browser.');
      setIsLocating(false);
    }
  };

  const updateMapCenter = (lat: number, lon: number) => {
    setCenterLat(lat);
    setCenterLon(lon);
    if (map && centerMarker && radiusCircle) {
      const latlng = new L.LatLng(lat, lon);
      map.setView(latlng, 13);
      centerMarker.setLatLng(latlng);
      radiusCircle.setLatLng(latlng);
      map.fitBounds(radiusCircle.getBounds(), { padding: [20, 20] });
    }
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    setGenerationError('');

    try {
      let checkCount = 10;
      if (sessionData && sessionData.ap_server_url) {
        // Mock API logic for now since this isn't connected to AP yet
        checkCount = 10;
      }

      console.log(`[Setup] Fetching Overpass data. Target nodes: ${checkCount}`);

      const intersections = await fetchCyclingIntersections(centerLat, centerLon, radius);

      if (intersections.length < checkCount) {
        throw new Error(`Found ${intersections.length} cycling intersections, but need ${checkCount}. Increase the radius or choose a denser area.`);
      }

      const selected = shuffleArray(intersections).slice(0, checkCount);
      console.log(`[Setup] Selected ${selected.length} nodes for the game.`);

      const nodePromises = selected.map((node, i) => {
        return pb.collection('map_nodes').create({
          session: seedId,
          ap_location_id: 800001 + i, // Base AP Location ID offset
          lat: node.lat,
          lon: node.lon,
          name: `Intersection ${node.id}`,
          state: 'Hidden'
        });
      });

      await Promise.all(nodePromises);

      await pb.collection('game_sessions').update(seedId, {
        center_lat: centerLat,
        center_lon: centerLon,
        radius,
        status: 'Active'
      });

      router.push(`/game/${seedId}`);
    } catch (e: any) {
      console.error(e);
      setGenerationError(e.message || 'Failed to generate nodes.');
    } finally {
      setIsGenerating(false);
    }
  };

  if (loadError) {
    return <div className="text-white p-8 text-center">{loadError}</div>;
  }

  return (
    <div className="flex flex-col h-screen bg-neutral-950 overflow-hidden">
      <header className="flex-none bg-neutral-900 border-b border-white/5 py-4 px-6 shadow-md z-10 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <button onClick={() => router.push('/new-game')} className="text-neutral-400 hover:text-white transition">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 18-6-6 6-6"/></svg>
          </button>
          <div>
            <div className="inline-flex items-center gap-2 px-2 py-0.5 rounded md bg-orange-500/10 text-orange-500 font-bold text-[10px] uppercase tracking-wider mb-1">
              Step 2 of 2
            </div>
            <h1 className="text-xl md:text-2xl font-bold text-white tracking-tight">Select Play Area</h1>
          </div>
        </div>
      </header>

      <div className="flex-1 flex flex-col md:flex-row min-h-0 relative">
        <div className="flex-1 relative order-2 md:order-1 h-[40vh] md:h-auto">
          <div ref={mapRef} className="absolute inset-0 z-0"></div>

          {/* Controls overlay for map */}
          <div className="absolute top-4 right-4 z-[400] flex flex-col gap-2">
            <button
              onClick={getUserLocation}
              disabled={isLocating}
              className="bg-neutral-900/90 backdrop-blur border border-white/10 hover:bg-neutral-800 text-white p-3 rounded-xl shadow-lg transition-colors flex items-center justify-center group"
              title="Find my location"
            >
              {isLocating ? (
                <svg className="animate-spin h-5 w-5 text-orange-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-neutral-400 group-hover:text-orange-500 transition-colors"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>
              )}
            </button>
          </div>
        </div>

        <div className="w-full md:w-[400px] lg:w-[450px] bg-neutral-900 border-l border-white/5 order-1 md:order-2 flex flex-col shadow-2xl z-10 shrink-0 h-[60vh] md:h-auto overflow-y-auto">
          <div className="p-6 md:p-8 flex-1 flex flex-col">
            <div className="mb-8">
              <p className="text-neutral-400 text-sm leading-relaxed">
                Choose the center point and radius for your game. Checks will be distributed to cycling-accessible intersections within this area.
              </p>
            </div>

            <div className="space-y-6">
              <div className="relative">
                <label className="block text-xs font-bold text-neutral-500 uppercase tracking-wider mb-2">
                  Search Address
                </label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={addressQuery}
                    onChange={(e) => setAddressQuery(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleGeocode()}
                    placeholder="e.g. Central Park, NY"
                    className="flex-1 bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white placeholder-neutral-600 focus:outline-none focus:ring-2 focus:ring-orange-500/50"
                  />
                  <button
                    onClick={handleGeocode}
                    disabled={isGeocoding}
                    className="bg-neutral-800 hover:bg-neutral-700 border border-white/5 text-white px-4 rounded-xl transition flex items-center justify-center disabled:opacity-50"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
                  </button>
                </div>
                {(geocodeError || locationError) && (
                  <p className="text-red-400 text-xs mt-2">{geocodeError || locationError}</p>
                )}
              </div>

              <div>
                <div className="flex justify-between items-end mb-2">
                  <label className="block text-xs font-bold text-neutral-500 uppercase tracking-wider">
                    Play Area Radius
                  </label>
                  <span className="text-orange-400 font-mono font-bold">
                    {(radius / 1000).toFixed(1)} km
                  </span>
                </div>
                <input
                  type="range"
                  min="1000"
                  max="20000"
                  step="500"
                  value={radius}
                  onChange={(e) => setRadius(Number(e.target.value))}
                  className="w-full h-2 bg-black/40 rounded-lg appearance-none cursor-pointer accent-orange-500 focus:outline-none focus:ring-2 focus:ring-orange-500/50"
                />
                <div className="flex justify-between text-xs text-neutral-600 mt-2 font-mono">
                  <span>1 km</span>
                  <span>20 km</span>
                </div>
              </div>

              <div className="bg-black/20 rounded-xl p-4 border border-white/5">
                <div className="flex items-start gap-3">
                  <div className="mt-0.5 text-neutral-500">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>
                  </div>
                  <div>
                    <p className="text-xs text-neutral-400 leading-relaxed">
                      Coordinates: <span className="text-white font-mono">{centerLat.toFixed(4)}, {centerLon.toFixed(4)}</span>
                    </p>
                    <p className="text-xs text-neutral-500 mt-1">
                      Drag the marker on the map to fine-tune your center point.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-auto pt-8">
              {generationError && (
                <div className="mb-4 p-3 bg-red-500/10 border border-red-500/20 text-red-400 text-sm rounded-xl">
                  {generationError}
                </div>
              )}

              <button
                onClick={handleGenerate}
                disabled={isGenerating}
                className="w-full group bg-orange-600 hover:bg-orange-500 text-white font-bold py-4 px-6 rounded-xl transition-all shadow-lg shadow-orange-900/20 disabled:opacity-50 flex items-center justify-center gap-3"
              >
                {isGenerating ? (
                  <>
                    <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                    Generating Map Data...
                  </>
                ) : (
                  <>
                    Start Session
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" className="group-hover:translate-x-1 transition-transform"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
